# -*- coding: utf-8 -*-
"""Reinhard Implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZRa0LIy9DnRxvBY3c9Y932-_NJVZmf68
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
def reinhard(source,target):
  source= cv2.resize(source,(600,600))
  target= cv2.resize(target,(600,600))
  source = cv2.cvtColor(source,cv2.COLOR_RGB2LAB)
  target = cv2.cvtColor(target,cv2.COLOR_RGB2LAB)
  l,a,b = cv2.split(source)
  l1,a1,b1 = cv2.split(target)
  x,y,z = l - np.mean(l),a- np.mean(a),b - np.mean(b)
  
  l2 = np.mean(l1) + (x)*(np.std(l1)/ np.std(l))
  a2 = np.mean(a1) + (y)*(np.std(a1)/ np.std(a))
  b2 = np.mean(b1) + (z)*(np.std(b1)/ np.std(b))
  result_image= cv2.merge((l2,a2,b2))
  
  return result_image


source_path ='x.jpg' #Path of the source Image
target_path = 'y.jpg' #Path of the target Image
source = cv2.imread(source_path)
target= cv2.imread(target_path)
cv2_imshow(reinhard(source,target))

